#!/usr/bin/env python3
"""Generate a versioned MOE opinion for one NFL game."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from types import SimpleNamespace

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
load_dotenv(ROOT / ".env.local")
load_dotenv(ROOT / ".env")

from moe import (
    approved_opinions,
    build_divisional_input,
    build_schedule_input,
    configured_opinion_store,
    generate_opinion,
    load_expert,
)
from moe_ak import build_ak_input
from moe_cee import build_cee_input
from moe_hi_lo import build_hi_lo_input
from moe_god import (
    AGGREGATOR_PROFILE,
    DETERMINISTIC_BACKEND,
    JUDGE_MODE,
    RULES_MODE,
    aggregator_policy,
    build_aggregator_input,
    build_judge_request,
    canonical_json,
    load_registry,
    sha256_text,
)
from moe_identity import (
    resolve_moe_expert_user_id_from_spreadsheet,
)
from moe_rating import RATING_MODE, RATING_PROFILE, build_rating_input
from moe_win_total import build_win_total_input
from nfl_game_annotations import (
    attach_game_annotations,
    load_game_annotations,
    with_game_annotation_context,
)
from intake_bot import (
    CELEBRITY_HEADERS,
    CELEBRITY_TAB,
    _celebrity_worksheet,
)
from nfl_game_history import (
    GAME_HISTORY_HEADERS,
    GAME_HISTORY_TAB,
    build_game_history,
    fetch_regular_season_events,
)
from nfl_lines import (
    GAME_HEADERS,
    LEAN_HEADERS,
    SNAPSHOT_HEADERS,
    get_gspread_client,
)
from nfl_schedule import SCHEDULE_HEADERS, SCHEDULE_TAB
from nfl_win_predictions import (
    PREDICTION_HEADERS,
    TEAM_HISTORY_HEADERS,
    WIN_TOTAL_HEADERS,
)


def _latest_alignment(history: list[dict]) -> list[dict]:
    alignment: dict[str, dict] = {}
    for row in sorted(history, key=lambda item: int(item["season"])):
        alignment[str(row["away_team"])] = {
            "team": str(row["away_team"]),
            "conference": str(row["away_conference"]),
            "division": str(row["away_division"]),
        }
        alignment[str(row["home_team"])] = {
            "team": str(row["home_team"]),
            "conference": str(row["home_conference"]),
            "division": str(row["home_division"]),
        }
    return list(alignment.values())


def current_season_finals(
    history: list[dict],
    season: int,
    annotation_rows: list[dict] | None = None,
) -> list[dict]:
    """ESPN finals for one season, shaped like nfl_game_history rows.

    Shared by the aggregator branch below and scripts/god_judge_runner.py.
    """
    events = fetch_regular_season_events(season, expected_games=None)
    return attach_game_annotations(
        build_game_history(
            {season: events},
            {season: _latest_alignment(history)},
            validate=False,
            require_complete_divisional_pairs=False,
        ),
        annotation_rows or [],
    )


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--event-id", required=True)
    parser.add_argument("--expert", default="schedule")
    parser.add_argument(
        "--model",
        help="Exact model ID. Defaults to the expert default, then MOE_MODEL.",
    )
    generation_mode = parser.add_mutually_exclusive_group(required=True)
    generation_mode.add_argument(
        "--show-input",
        action="store_true",
        help="Print the enforced expert input package without calling a model.",
    )
    generation_mode.add_argument(
        "--agent-response",
        type=Path,
        help=(
            "Persist and validate raw opinion JSON generated by an agent "
            "instead of calling the Anthropic API."
        ),
    )
    generation_mode.add_argument(
        "--api",
        action="store_true",
        help=(
            "Explicitly call the application's Anthropic API. Agent-session "
            "generation is the preferred workflow."
        ),
    )
    generation_mode.add_argument(
        "--deterministic",
        action="store_true",
        help=(
            "Run a deterministic expert (god_rules, or a mode-model expert "
            "such as rating_elo). No model is called; the computed opinion "
            "is persisted like any other."
        ),
    )
    parser.add_argument(
        "--agent-factuality-response",
        type=Path,
        help=(
            "Raw factuality JSON from a second agent. Required with "
            "--agent-response for output schema v4."
        ),
    )
    parser.add_argument(
        "--generation-effort",
        choices=("low", "medium", "high", "xhigh", "max"),
        help=(
            "Actual agent-session reasoning effort. Overrides the registered "
            "model effort only with --agent-response."
        ),
    )
    parser.add_argument(
        "--expected-input-sha256",
        help=(
            "SHA-256 printed by --show-input. With --agent-response, refuse "
            "to persist if the rebuilt input no longer matches it."
        ),
    )
    parser.add_argument(
        "--input-file",
        type=Path,
        help=(
            "JSON file holding the full aggregator input, as printed by "
            "--expert god_rules --show-input. The rules arm persists it "
            "verbatim; the judge persists the request derived from it. Valid "
            "with --deterministic, --agent-response, and --show-input; the "
            "sheet's opinions, snapshots, and finals are not read."
        ),
    )
    parser.add_argument(
        "--generation-backend",
        choices=("agent_runtime", "claude_headless"),
        help=(
            "How the --agent-response was produced (default agent_runtime; "
            "claude_headless is the timer's headless claude -p call)."
        ),
    )
    args = parser.parse_args()
    if args.generation_effort and not args.agent_response:
        parser.error("--generation-effort requires --agent-response")
    if args.expected_input_sha256 and not args.agent_response:
        parser.error("--expected-input-sha256 requires --agent-response")
    if args.generation_backend and not args.agent_response:
        parser.error("--generation-backend requires --agent-response")
    if args.input_file and args.api:
        parser.error("--input-file is not valid with --api")

    credentials = os.environ.get("GOOGLE_CREDENTIALS", "")
    sheet_id = os.environ.get("NFL_INTAKE_SHEET_ID", "")
    if not credentials or not sheet_id:
        raise RuntimeError(
            "GOOGLE_CREDENTIALS and NFL_INTAKE_SHEET_ID are required"
        )
    spreadsheet = get_gspread_client(credentials).open_by_key(sheet_id)
    games = spreadsheet.worksheet("nfl_games").get_all_records(
        expected_headers=GAME_HEADERS
    )
    history = spreadsheet.worksheet(GAME_HISTORY_TAB).get_all_records(
        expected_headers=GAME_HISTORY_HEADERS
    )
    annotation_rows = load_game_annotations(spreadsheet)
    history = attach_game_annotations(history, annotation_rows)
    game = next(
        (
            row
            for row in games
            if str(row.get("event_id")) == str(args.event_id)
        ),
        None,
    )
    if game is None:
        raise ValueError(f"Unknown nfl_games event_id: {args.event_id}")
    base_expert = load_expert(args.expert)
    selected_model = (
        args.model
        or str(base_expert.get("default_model") or "")
        or os.getenv("MOE_MODEL")
        or "claude-sonnet-4-6"
    )
    expert = load_expert(args.expert, model=selected_model)
    expert_mode = str(expert.get("mode") or "")
    if args.deterministic and expert_mode not in {RULES_MODE, RATING_MODE}:
        parser.error(
            "--deterministic is only valid for the rules aggregator and "
            "deterministic model experts (mode model)"
        )
    if expert_mode in {RULES_MODE, RATING_MODE} and not (
        args.deterministic or args.show_input
    ):
        parser.error(
            f"Expert {args.expert} requires --deterministic or --show-input"
        )
    if args.input_file and expert["input_profile"] != AGGREGATOR_PROFILE:
        parser.error("--input-file is only valid for the aggregator experts")
    prebuilt: dict | None = None
    if args.input_file:
        prebuilt = json.loads(args.input_file.read_text(encoding="utf-8"))
        if not isinstance(prebuilt, dict):
            parser.error("--input-file must hold one JSON object")
    if args.api and "anthropic_api" not in {
        str(value)
        for value in expert.get("allowed_backends", ["anthropic_api"])
    }:
        parser.error(f"--api is not allowed for expert {args.expert}")
    if args.agent_factuality_response and not args.agent_response:
        parser.error(
            "--agent-factuality-response requires --agent-response"
        )
    needs_factuality = int(expert["output_schema_version"]) == 4
    if args.agent_response and needs_factuality != bool(
        args.agent_factuality_response
    ):
        parser.error(
            "Schema-v4 experts require both --agent-response and "
            "--agent-factuality-response; other schemas require only "
            "--agent-response"
        )
    schedule: list[dict] | None = None
    current_results: list[dict] | None = None
    leans: list[dict] | None = None
    line_snapshots: list[dict] | None = None
    ak_user_id: str | None = None
    cee_user_id: str | None = None
    celebrity_picks: list[dict] | None = None
    win_totals: list[dict] | None = None
    win_predictions: list[dict] | None = None
    team_history: list[dict] | None = None
    opinions: list[dict] | None = None
    store = configured_opinion_store()

    def _current_results() -> list[dict]:
        return current_season_finals(
            history,
            int(game["season"]),
            annotation_rows,
        )

    if expert["input_profile"] == "divisional":
        schedule = spreadsheet.worksheet(SCHEDULE_TAB).get_all_records(
            expected_headers=SCHEDULE_HEADERS
        )
        current_results = _current_results()
    elif expert["input_profile"] == AGGREGATOR_PROFILE and prebuilt is None:
        # With --input-file the file is the state: no opinions, snapshots,
        # or finals are read, so nothing can drift between show and persist.
        current_results = _current_results()
        line_snapshots = spreadsheet.worksheet(
            "nfl_line_snapshots"
        ).get_all_records(expected_headers=SNAPSHOT_HEADERS)
        opinions = store.list()
    elif expert["input_profile"] == RATING_PROFILE:
        # Preseason ratings plus this season's finals before kickoff.
        current_results = _current_results()
    elif expert["input_profile"] == "ak_calibration":
        ak_user_id = resolve_moe_expert_user_id_from_spreadsheet(
            spreadsheet,
            "ak",
        )
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
        line_snapshots = spreadsheet.worksheet(
            "nfl_line_snapshots"
        ).get_all_records(expected_headers=SNAPSHOT_HEADERS)
    elif expert["input_profile"] == "cee_calibration":
        current_results = _current_results()
        cee_user_id = resolve_moe_expert_user_id_from_spreadsheet(
            spreadsheet,
            "cee",
        )
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
        win_predictions = spreadsheet.worksheet(
            "nfl_win_predictions"
        ).get_all_records(expected_headers=PREDICTION_HEADERS)
    elif expert["input_profile"] == "celebrity_patterns":
        current_results = _current_results()
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
        celebrity_picks = _celebrity_worksheet(
            spreadsheet
        ).get_all_records(expected_headers=CELEBRITY_HEADERS)
    elif expert["input_profile"] == "win_total":
        win_totals = spreadsheet.worksheet(
            "nfl_win_totals"
        ).get_all_records(expected_headers=WIN_TOTAL_HEADERS)
        win_predictions = spreadsheet.worksheet(
            "nfl_win_predictions"
        ).get_all_records(expected_headers=PREDICTION_HEADERS)
        team_history = spreadsheet.worksheet(
            "nfl_team_history"
        ).get_all_records(expected_headers=TEAM_HISTORY_HEADERS)
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
        leans.extend(
            spreadsheet.worksheet(CELEBRITY_TAB).get_all_records(
                expected_headers=CELEBRITY_HEADERS
            )
        )
    if args.show_input:
        if expert["input_profile"] == "schedule_only":
            input_payload = build_schedule_input(game, history)
        elif expert["input_profile"] == "divisional":
            input_payload = build_divisional_input(
                game,
                history,
                schedule or [],
                current_results,
            )
        elif expert["input_profile"] == "ak_calibration":
            input_payload = build_ak_input(
                game,
                history,
                leans or [],
                line_snapshots,
                ak_user_id=ak_user_id or "",
            )
        elif expert["input_profile"] == "cee_calibration":
            input_payload = build_cee_input(
                game,
                [*history, *(current_results or [])],
                leans or [],
                win_predictions or [],
                cee_user_id=cee_user_id or "",
            )
        elif expert["input_profile"] == "celebrity_patterns":
            from moe_celebrity import build_celebrity_input

            input_payload = build_celebrity_input(
                game,
                [*history, *(current_results or [])],
                celebrity_picks or [],
                leans or [],
            )
        elif expert["input_profile"] == "win_total":
            input_payload = build_win_total_input(
                game,
                history,
                win_totals or [],
                win_predictions or [],
                team_history or [],
                leans or [],
            )
        elif expert["input_profile"] == "hi_lo_outliers":
            input_payload = build_hi_lo_input(game, games)
        elif expert["input_profile"] == RATING_PROFILE:
            input_payload = build_rating_input(game, current_results or [])
        elif expert["input_profile"] == AGGREGATOR_PROFILE:
            if prebuilt is not None:
                # The rules arm re-prints the file's canonical form and its
                # hash; the judge prints the request derived from the file.
                if str((prebuilt.get("game") or {}).get("event_id")) != str(
                    args.event_id
                ):
                    raise ValueError("--input-file describes a different event")
                input_payload = prebuilt
            else:
                registry = load_registry()
                input_payload = build_aggregator_input(
                    game,
                    approved_opinions=approved_opinions(opinions or []),
                    finals=current_results or [],
                    snapshots=line_snapshots or [],
                    registry=registry,
                    policy=aggregator_policy(registry),
                )
            if expert_mode == JUDGE_MODE:
                # What the judge model reads: masked voices, shuffled by seed.
                input_payload = build_judge_request(input_payload)
        else:
            raise NotImplementedError(
                f"Unsupported input profile: {expert['input_profile']}"
            )
        if prebuilt is None:
            annotation_games = (
                list(current_results or [])
                if expert["input_profile"]
                in {AGGREGATOR_PROFILE, RATING_PROFILE}
                else [*history, *(current_results or [])]
            )
            input_payload = with_game_annotation_context(
                input_payload,
                annotation_games,
                deterministic_treatment=(
                    "include"
                    if expert["input_profile"]
                    in {AGGREGATOR_PROFILE, RATING_PROFILE}
                    else "not_applicable"
                ),
            )
        print(
            json.dumps(
                input_payload,
                indent=2,
                sort_keys=True,
            )
        )
        # The hash of the exact input generate_opinion will persist; pass it
        # back as --expected-input-sha256 so a sheet change between the
        # inference and the persist fails closed instead of misfiling.
        print(
            f"input_sha256={sha256_text(canonical_json(input_payload))}",
            file=sys.stderr,
        )
        return

    create_fn = None
    generation_backend = "anthropic_api"
    if args.deterministic:
        generation_backend = DETERMINISTIC_BACKEND
    if args.agent_response:
        responses = [args.agent_response.read_text(encoding="utf-8")]
        if args.agent_factuality_response:
            responses.append(
                args.agent_factuality_response.read_text(encoding="utf-8")
            )

        async def agent_create_fn(**_kwargs):
            if not responses:
                raise RuntimeError("No unused agent response remains")
            return SimpleNamespace(
                content=[SimpleNamespace(text=responses.pop(0))]
            )

        create_fn = agent_create_fn
        generation_backend = args.generation_backend or "agent_runtime"

    generation_kwargs = {}
    if create_fn is not None:
        generation_kwargs["create_fn"] = create_fn
    opinion = await generate_opinion(
        expert_id=args.expert,
        game=game,
        history=(
            [*history, *(current_results or [])]
            if expert["input_profile"]
            in {"celebrity_patterns", "cee_calibration"}
            else history
        ),
        games=games,
        schedule=schedule,
        current_season_results=current_results,
        leans=leans,
        line_snapshots=line_snapshots,
        ak_user_id=ak_user_id,
        cee_user_id=cee_user_id,
        celebrity_picks=celebrity_picks,
        win_totals=win_totals,
        win_predictions=win_predictions,
        team_history=team_history,
        opinions=opinions,
        input_payload=prebuilt,
        store=store,
        model=args.model,
        generation_backend=generation_backend,
        generation_effort=args.generation_effort,
        expected_input_sha256=args.expected_input_sha256,
        repair_attempts=(
            2
            if create_fn is None
            and int(expert["output_schema_version"]) in {3, 4, 5, 6}
            else 0
        ),
        **generation_kwargs,
    )
    print(
        f"{opinion['expert_name']}: {opinion['predicted_winner']} | "
        f"score {opinion['predicted_away_score']}-"
        f"{opinion['predicted_home_score']} | "
        f"home {opinion['home_win_probability']:.0%} | "
        f"margin {opinion['expected_home_margin']:+.1f} | "
        f"{'★' * opinion['confidence_stars']}"
    )
    print(opinion["full_opinion"])
    print(f"Persisted opinion {opinion['opinion_id']} to moe_opinions.")


if __name__ == "__main__":
    asyncio.run(main())
