#!/usr/bin/env python3
"""Generate a versioned MOE opinion for one NFL game."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from types import SimpleNamespace

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
load_dotenv(ROOT / ".env.local")
load_dotenv(ROOT / ".env")

from moe import (
    build_divisional_input,
    build_schedule_input,
    configured_opinion_store,
    generate_opinion,
    load_expert,
)
from moe_ak import build_ak_input
from moe_win_total import build_win_total_input
from nfl_game_history import (
    GAME_HISTORY_HEADERS,
    GAME_HISTORY_TAB,
    build_game_history,
    fetch_regular_season_events,
)
from nfl_lines import (
    GAME_HEADERS,
    LEAN_HEADERS,
    SNAPSHOT_HEADERS,
    get_gspread_client,
)
from nfl_schedule import SCHEDULE_HEADERS, SCHEDULE_TAB
from nfl_win_predictions import (
    PREDICTION_HEADERS,
    TEAM_HISTORY_HEADERS,
    WIN_TOTAL_HEADERS,
)


def _latest_alignment(history: list[dict]) -> list[dict]:
    alignment: dict[str, dict] = {}
    for row in sorted(history, key=lambda item: int(item["season"])):
        alignment[str(row["away_team"])] = {
            "team": str(row["away_team"]),
            "conference": str(row["away_conference"]),
            "division": str(row["away_division"]),
        }
        alignment[str(row["home_team"])] = {
            "team": str(row["home_team"]),
            "conference": str(row["home_conference"]),
            "division": str(row["home_division"]),
        }
    return list(alignment.values())


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--event-id", required=True)
    parser.add_argument("--expert", default="schedule")
    parser.add_argument(
        "--model",
        help="Exact model ID. Defaults to the expert default, then MOE_MODEL.",
    )
    parser.add_argument(
        "--show-input",
        action="store_true",
        help="Print the enforced expert input package without calling a model.",
    )
    parser.add_argument(
        "--agent-response",
        type=Path,
        help=(
            "Persist and validate raw opinion JSON generated by an agent "
            "instead of calling the Anthropic API."
        ),
    )
    parser.add_argument(
        "--agent-factuality-response",
        type=Path,
        help=(
            "Raw factuality JSON from a second agent. Required with "
            "--agent-response for output schema v4."
        ),
    )
    args = parser.parse_args()

    credentials = os.environ.get("GOOGLE_CREDENTIALS", "")
    sheet_id = os.environ.get("NFL_INTAKE_SHEET_ID", "")
    if not credentials or not sheet_id:
        raise RuntimeError(
            "GOOGLE_CREDENTIALS and NFL_INTAKE_SHEET_ID are required"
        )
    spreadsheet = get_gspread_client(credentials).open_by_key(sheet_id)
    games = spreadsheet.worksheet("nfl_games").get_all_records(
        expected_headers=GAME_HEADERS
    )
    history = spreadsheet.worksheet(GAME_HISTORY_TAB).get_all_records(
        expected_headers=GAME_HISTORY_HEADERS
    )
    game = next(
        (
            row
            for row in games
            if str(row.get("event_id")) == str(args.event_id)
        ),
        None,
    )
    if game is None:
        raise ValueError(f"Unknown nfl_games event_id: {args.event_id}")
    expert = load_expert(args.expert)
    if args.agent_factuality_response and not args.agent_response:
        parser.error(
            "--agent-factuality-response requires --agent-response"
        )
    needs_factuality = int(expert["output_schema_version"]) == 4
    if args.agent_response and needs_factuality != bool(
        args.agent_factuality_response
    ):
        parser.error(
            "Schema-v4 experts require both --agent-response and "
            "--agent-factuality-response; other schemas require only "
            "--agent-response"
        )
    schedule: list[dict] | None = None
    current_results: list[dict] | None = None
    leans: list[dict] | None = None
    line_snapshots: list[dict] | None = None
    ak_user_id: str | None = None
    win_totals: list[dict] | None = None
    win_predictions: list[dict] | None = None
    team_history: list[dict] | None = None
    if expert["input_profile"] == "divisional":
        schedule = spreadsheet.worksheet(SCHEDULE_TAB).get_all_records(
            expected_headers=SCHEDULE_HEADERS
        )
        season = int(game["season"])
        current_events = fetch_regular_season_events(
            season, expected_games=None
        )
        current_results = build_game_history(
            {season: current_events},
            {season: _latest_alignment(history)},
            validate=False,
            require_complete_divisional_pairs=False,
        )
    elif expert["input_profile"] == "ak_calibration":
        ak_user_id = os.environ.get("AK_TELEGRAM_USER_ID", "").strip()
        if not ak_user_id:
            raise RuntimeError("AK_TELEGRAM_USER_ID is required")
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
        line_snapshots = spreadsheet.worksheet(
            "nfl_line_snapshots"
        ).get_all_records(expected_headers=SNAPSHOT_HEADERS)
    elif expert["input_profile"] == "win_total":
        win_totals = spreadsheet.worksheet(
            "nfl_win_totals"
        ).get_all_records(expected_headers=WIN_TOTAL_HEADERS)
        win_predictions = spreadsheet.worksheet(
            "nfl_win_predictions"
        ).get_all_records(expected_headers=PREDICTION_HEADERS)
        team_history = spreadsheet.worksheet(
            "nfl_team_history"
        ).get_all_records(expected_headers=TEAM_HISTORY_HEADERS)
        leans = spreadsheet.worksheet("nfl_leans").get_all_records(
            expected_headers=LEAN_HEADERS
        )
    if args.show_input:
        if expert["input_profile"] == "schedule_only":
            input_payload = build_schedule_input(game, history)
        elif expert["input_profile"] == "divisional":
            input_payload = build_divisional_input(
                game,
                history,
                schedule or [],
                current_results,
            )
        elif expert["input_profile"] == "ak_calibration":
            input_payload = build_ak_input(
                game,
                history,
                leans or [],
                line_snapshots,
                ak_user_id=ak_user_id or "",
            )
        elif expert["input_profile"] == "win_total":
            input_payload = build_win_total_input(
                game,
                history,
                win_totals or [],
                win_predictions or [],
                team_history or [],
                leans or [],
            )
        else:
            raise NotImplementedError(
                f"Unsupported input profile: {expert['input_profile']}"
            )
        print(
            json.dumps(
                input_payload,
                indent=2,
                sort_keys=True,
            )
        )
        return

    create_fn = None
    generation_backend = "anthropic_api"
    if args.agent_response:
        responses = [args.agent_response.read_text(encoding="utf-8")]
        if args.agent_factuality_response:
            responses.append(
                args.agent_factuality_response.read_text(encoding="utf-8")
            )

        async def agent_create_fn(**_kwargs):
            if not responses:
                raise RuntimeError("No unused agent response remains")
            return SimpleNamespace(
                content=[SimpleNamespace(text=responses.pop(0))]
            )

        create_fn = agent_create_fn
        generation_backend = "agent_runtime"

    generation_kwargs = {}
    if create_fn is not None:
        generation_kwargs["create_fn"] = create_fn
    opinion = await generate_opinion(
        expert_id=args.expert,
        game=game,
        history=history,
        schedule=schedule,
        current_season_results=current_results,
        leans=leans,
        line_snapshots=line_snapshots,
        ak_user_id=ak_user_id,
        win_totals=win_totals,
        win_predictions=win_predictions,
        team_history=team_history,
        store=configured_opinion_store(),
        model=args.model,
        generation_backend=generation_backend,
        repair_attempts=(
            2
            if create_fn is None
            and int(expert["output_schema_version"]) in {3, 4, 5, 6}
            else 0
        ),
        **generation_kwargs,
    )
    print(
        f"{opinion['expert_name']}: {opinion['predicted_winner']} | "
        f"score {opinion['predicted_away_score']}-"
        f"{opinion['predicted_home_score']} | "
        f"home {opinion['home_win_probability']:.0%} | "
        f"margin {opinion['expected_home_margin']:+.1f} | "
        f"{'★' * opinion['confidence_stars']}"
    )
    print(opinion["full_opinion"])
    print(f"Persisted opinion {opinion['opinion_id']} to moe_opinions.")


if __name__ == "__main__":
    asyncio.run(main())
